version: "3.8"

services:
  db_movie:
    image: postgres:11-alpine
    container_name: db_movie
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    build: .
    container_name: django
    command:  bash -c "python /usr/src/django_movie/manage.py makemigrations &&
              python /usr/src/django_movie/manage.py migrate --noinput &&
              python /usr/src/django_movie/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/django_movie
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    depends_on:
      - db_movie
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A django_movie worker -l info
    volumes:
      - .:/code
    depends_on:
      - db_movie
      - redis
    env_file:
      - .env.dev

#  redis:
#    image: redis:5-alpine
#    restart: always


volumes:
  postgres_data: