# Generated by Django 4.0.6 on 2022-08-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_addres',
            name='movie',
            field=models.ManyToManyField(related_name='ip', to='movies.movie', verbose_name='фильм'),
        ),
        migrations.AlterField(
            model_name='likedislikereview',
            name='Review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedislikereview', to='movies.review', verbose_name='звезда'),
        ),
    ]
