# Generated by Django 4.0.6 on 2022-08-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_imdb_movie_kr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Слоган'),
        ),
    ]
